### ISSUE TITLE
Neues Attribut anlegen, löschen

### ISSUE THREAD

**Issue by thecodemonkey** [openvalidation/openvalidation-ide#13]
Es soll möglich sein ein neues Schema-Attribute anzulegen. Es gibt einen Chip mit einem + über den man ein neues Attribut erstellt. Beim klick wird ein neuer chip erstellt mit einem Eingabefeld und einem Blinkendem Cursor. Nach der Eingabe des Namens und der Bestätigung

**Comment by Jaykju** [comment]
Connect frontend and backend schema functionalities.
