### ISSUE TITLE
Ruleset card design

### ISSUE THREAD

**Issue by aletutto** [openvalidation/openvalidation-ide#38]
- Title (cut after one line with three dots)
- Description (only display two lines of the description and cut with three dots)
- Date
- User

All cards should have the same size.
Hover effect: Card shadow + move top left + title glow effect

~Edit the card:~
- ~Edit icon on hover on title~
- ~Edit icon on hover on description~

See mockup for margin and paddings.

Add Card:
Should include a centered plus-button.
Blank otherwise - no title and no description.

**Comment by Jaykju** [comment]
After a discussion it was decided that there should not be any editing functionality in the overview
